name: sertifikasi_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  d_info: ^0.2.2
  d_view: ^0.0.5
  d_input: ^0.1.3
  http: ^0.13.3
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
